name: building, testing, linting
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Starting NodeJS
        uses: actions/setup-node@1.4.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install modules
        run: npm i --save --legacy-peer-deps
      - name: Build project
        if: always()
        run: npm run build
      - name: Linting Typescript
        if: always()
        run: npm run lint:ts
      - name: Linting CSS
        if: always()
        run: npm run lint:css
      - name: Unit Testing
        if: always()
        run: npm run test